//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMERG_DBEntities : DbContext
    {
        public EMERG_DBEntities()
            : base("name=EMERG_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_EM_DOCUMENTS> T_EM_DOCUMENTS { get; set; }
        public virtual DbSet<T_EM_INCIDENT> T_EM_INCIDENT { get; set; }
        public virtual DbSet<T_EM_INCIDENT_ACTIONS> T_EM_INCIDENT_ACTIONS { get; set; }
        public virtual DbSet<T_EM_INCIDENT_ATTACH> T_EM_INCIDENT_ATTACH { get; set; }
        public virtual DbSet<T_EM_INCIDENT_LOC_AREA> T_EM_INCIDENT_LOC_AREA { get; set; }
        public virtual DbSet<T_EM_INCIDENT_OBJECTIVES> T_EM_INCIDENT_OBJECTIVES { get; set; }
        public virtual DbSet<T_EM_INCIDENT_OP_PERIOD> T_EM_INCIDENT_OP_PERIOD { get; set; }
        public virtual DbSet<T_EM_INCIDENT_RESOURCES> T_EM_INCIDENT_RESOURCES { get; set; }
        public virtual DbSet<T_EM_INCIDENT_STATUS> T_EM_INCIDENT_STATUS { get; set; }
        public virtual DbSet<T_EM_INCIDENT_TEAM_DTL> T_EM_INCIDENT_TEAM_DTL { get; set; }
        public virtual DbSet<T_EM_INDIVIDUALS> T_EM_INDIVIDUALS { get; set; }
        public virtual DbSet<T_EM_QUALIFICATIONS> T_EM_QUALIFICATIONS { get; set; }
        public virtual DbSet<T_EM_REF_COMPLEX_LVL> T_EM_REF_COMPLEX_LVL { get; set; }
        public virtual DbSet<T_EM_REF_DOC_STATUS_TYPE> T_EM_REF_DOC_STATUS_TYPE { get; set; }
        public virtual DbSet<T_EM_REF_DOC_TYPE> T_EM_REF_DOC_TYPE { get; set; }
        public virtual DbSet<T_EM_REF_INC_STATUS_TYPE> T_EM_REF_INC_STATUS_TYPE { get; set; }
        public virtual DbSet<T_EM_REF_MANAGEMENT_ORG> T_EM_REF_MANAGEMENT_ORG { get; set; }
        public virtual DbSet<T_EM_REF_QUAL_CATEGORY> T_EM_REF_QUAL_CATEGORY { get; set; }
        public virtual DbSet<T_EM_REF_QUAL_TYPE> T_EM_REF_QUAL_TYPE { get; set; }
        public virtual DbSet<T_EM_REF_QUAL_TYPE_REQ> T_EM_REF_QUAL_TYPE_REQ { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_CAT> T_EM_REF_RESOURCE_CAT { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_CORE_CAP> T_EM_REF_RESOURCE_CORE_CAP { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_DISCIPLINE> T_EM_REF_RESOURCE_DISCIPLINE { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_KIND> T_EM_REF_RESOURCE_KIND { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_TYPE> T_EM_REF_RESOURCE_TYPE { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_TYPE_DTL> T_EM_REF_RESOURCE_TYPE_DTL { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_TYPE_DTL_DATA> T_EM_REF_RESOURCE_TYPE_DTL_DATA { get; set; }
        public virtual DbSet<T_EM_REF_SHARE_TYPE> T_EM_REF_SHARE_TYPE { get; set; }
        public virtual DbSet<T_EM_RESOURCE> T_EM_RESOURCE { get; set; }
        public virtual DbSet<T_EM_RESOURCE_DTL> T_EM_RESOURCE_DTL { get; set; }
        public virtual DbSet<T_EM_RESOURCE_VER_HIST> T_EM_RESOURCE_VER_HIST { get; set; }
        public virtual DbSet<T_EM_USER_NOTIFICATION> T_EM_USER_NOTIFICATION { get; set; }
        public virtual DbSet<T_EM_USER_ORG> T_EM_USER_ORG { get; set; }
        public virtual DbSet<T_OE_APP_SETTINGS> T_OE_APP_SETTINGS { get; set; }
        public virtual DbSet<T_OE_ORGANIZATIONS> T_OE_ORGANIZATIONS { get; set; }
        public virtual DbSet<T_OE_ROLES> T_OE_ROLES { get; set; }
        public virtual DbSet<T_OE_SYS_EMAIL_LOG> T_OE_SYS_EMAIL_LOG { get; set; }
        public virtual DbSet<T_OE_SYS_LOG> T_OE_SYS_LOG { get; set; }
        public virtual DbSet<T_OE_USER_ROLES> T_OE_USER_ROLES { get; set; }
        public virtual DbSet<T_OE_USERS> T_OE_USERS { get; set; }
        public virtual DbSet<V_EM_INCIDENT_TEAM_DISPLAY> V_EM_INCIDENT_TEAM_DISPLAY { get; set; }
        public virtual DbSet<V_EM_TIMELINE> V_EM_TIMELINE { get; set; }
        public virtual DbSet<T_EM_REF_RESOURCE_STATUS> T_EM_REF_RESOURCE_STATUS { get; set; }
        public virtual DbSet<T_EM_REF_INCIDENT_PRIORITY> T_EM_REF_INCIDENT_PRIORITY { get; set; }
        public virtual DbSet<T_EM_QUALIFICATION_ATTACH> T_EM_QUALIFICATION_ATTACH { get; set; }
        public virtual DbSet<T_OE_USER_TOKENS> T_OE_USER_TOKENS { get; set; }
        public virtual DbSet<T_EM_USER_LOCATION> T_EM_USER_LOCATION { get; set; }
    
        public virtual ObjectResult<SP_DASHBOARD_COUNTS_Result> SP_DASHBOARD_COUNTS(Nullable<int> userIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_COUNTS_Result>("SP_DASHBOARD_COUNTS", userIDXParameter);
        }
    
        public virtual ObjectResult<SP_RESOURCE_DTL_Result> SP_RESOURCE_DTL(Nullable<System.Guid> resourceIDX)
        {
            var resourceIDXParameter = resourceIDX.HasValue ?
                new ObjectParameter("ResourceIDX", resourceIDX) :
                new ObjectParameter("ResourceIDX", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RESOURCE_DTL_Result>("SP_RESOURCE_DTL", resourceIDXParameter);
        }
    
        public virtual ObjectResult<SP_INCIDENT_ADV_SEARCH_Result> SP_INCIDENT_ADV_SEARCH(Nullable<int> userIDX, Nullable<System.Guid> orgIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            var orgIDXParameter = orgIDX.HasValue ?
                new ObjectParameter("OrgIDX", orgIDX) :
                new ObjectParameter("OrgIDX", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INCIDENT_ADV_SEARCH_Result>("SP_INCIDENT_ADV_SEARCH", userIDXParameter, orgIDXParameter);
        }
    
        public virtual ObjectResult<SP_RESOURCE_DTL_ADV_SEARCH_Result> SP_RESOURCE_DTL_ADV_SEARCH(Nullable<int> userIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RESOURCE_DTL_ADV_SEARCH_Result>("SP_RESOURCE_DTL_ADV_SEARCH", userIDXParameter);
        }
    
        public virtual ObjectResult<SP_INCIDENT_STATUS_QUERY_Result> SP_INCIDENT_STATUS_QUERY(Nullable<int> userIDX, Nullable<System.Guid> orgIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            var orgIDXParameter = orgIDX.HasValue ?
                new ObjectParameter("OrgIDX", orgIDX) :
                new ObjectParameter("OrgIDX", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INCIDENT_STATUS_QUERY_Result>("SP_INCIDENT_STATUS_QUERY", userIDXParameter, orgIDXParameter);
        }
    
        public virtual ObjectResult<SP_RESOURCE_ADV_SEARCH_Result> SP_RESOURCE_ADV_SEARCH(Nullable<int> userIDX, Nullable<System.Guid> orgIDX, string resourceStr, Nullable<decimal> latMax, Nullable<decimal> latMin, Nullable<decimal> longMax, Nullable<decimal> longMin, string kind, string statusCd)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            var orgIDXParameter = orgIDX.HasValue ?
                new ObjectParameter("OrgIDX", orgIDX) :
                new ObjectParameter("OrgIDX", typeof(System.Guid));
    
            var resourceStrParameter = resourceStr != null ?
                new ObjectParameter("ResourceStr", resourceStr) :
                new ObjectParameter("ResourceStr", typeof(string));
    
            var latMaxParameter = latMax.HasValue ?
                new ObjectParameter("LatMax", latMax) :
                new ObjectParameter("LatMax", typeof(decimal));
    
            var latMinParameter = latMin.HasValue ?
                new ObjectParameter("LatMin", latMin) :
                new ObjectParameter("LatMin", typeof(decimal));
    
            var longMaxParameter = longMax.HasValue ?
                new ObjectParameter("LongMax", longMax) :
                new ObjectParameter("LongMax", typeof(decimal));
    
            var longMinParameter = longMin.HasValue ?
                new ObjectParameter("LongMin", longMin) :
                new ObjectParameter("LongMin", typeof(decimal));
    
            var kindParameter = kind != null ?
                new ObjectParameter("kind", kind) :
                new ObjectParameter("kind", typeof(string));
    
            var statusCdParameter = statusCd != null ?
                new ObjectParameter("statusCd", statusCd) :
                new ObjectParameter("statusCd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RESOURCE_ADV_SEARCH_Result>("SP_RESOURCE_ADV_SEARCH", userIDXParameter, orgIDXParameter, resourceStrParameter, latMaxParameter, latMinParameter, longMaxParameter, longMinParameter, kindParameter, statusCdParameter);
        }
    
        public virtual ObjectResult<SP_INCIDENT_RESOURCE_QUERY_Result> SP_INCIDENT_RESOURCE_QUERY(Nullable<int> userIDX, Nullable<System.Guid> orgIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            var orgIDXParameter = orgIDX.HasValue ?
                new ObjectParameter("OrgIDX", orgIDX) :
                new ObjectParameter("OrgIDX", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INCIDENT_RESOURCE_QUERY_Result>("SP_INCIDENT_RESOURCE_QUERY", userIDXParameter, orgIDXParameter);
        }
    
        public virtual ObjectResult<SP_INCIDENT_OP_PERIOD_QUERY_Result> SP_INCIDENT_OP_PERIOD_QUERY(Nullable<int> userIDX, Nullable<System.Guid> orgIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            var orgIDXParameter = orgIDX.HasValue ?
                new ObjectParameter("OrgIDX", orgIDX) :
                new ObjectParameter("OrgIDX", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INCIDENT_OP_PERIOD_QUERY_Result>("SP_INCIDENT_OP_PERIOD_QUERY", userIDXParameter, orgIDXParameter);
        }
    
        public virtual ObjectResult<SP_INCIDENT_TEAM_QUERY_Result> SP_INCIDENT_TEAM_QUERY(Nullable<int> userIDX, Nullable<System.Guid> orgIDX)
        {
            var userIDXParameter = userIDX.HasValue ?
                new ObjectParameter("UserIDX", userIDX) :
                new ObjectParameter("UserIDX", typeof(int));
    
            var orgIDXParameter = orgIDX.HasValue ?
                new ObjectParameter("OrgIDX", orgIDX) :
                new ObjectParameter("OrgIDX", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INCIDENT_TEAM_QUERY_Result>("SP_INCIDENT_TEAM_QUERY", userIDXParameter, orgIDXParameter);
        }
    }
}
