//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_REF_RESOURCE_TYPE_DTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EM_REF_RESOURCE_TYPE_DTL()
        {
            this.T_EM_REF_RESOURCE_TYPE_DTL_DATA = new HashSet<T_EM_REF_RESOURCE_TYPE_DTL_DATA>();
            this.T_EM_RESOURCE_DTL = new HashSet<T_EM_RESOURCE_DTL>();
        }
    
        public System.Guid RESOURCE_TYPE_DTL_IDX { get; set; }
        public System.Guid RESOURCE_TYPE_IDX { get; set; }
        public string COMPONENT { get; set; }
        public string METRIC { get; set; }
        public string CAPABILITY { get; set; }
        public Nullable<int> ORDERING_SEQ { get; set; }
        public string COMMENTS { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_EM_REF_RESOURCE_TYPE T_EM_REF_RESOURCE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_REF_RESOURCE_TYPE_DTL_DATA> T_EM_REF_RESOURCE_TYPE_DTL_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_RESOURCE_DTL> T_EM_RESOURCE_DTL { get; set; }
    }
}
