//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_RESOURCE_VER_HIST
    {
        public System.Guid RESOURCE_VER_HIST_IDX { get; set; }
        public System.Guid RESOURCE_IDX { get; set; }
        public Nullable<System.DateTime> VERIFICATION_DT { get; set; }
        public Nullable<int> VERIFIED_BY_IDX { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
    
        public virtual T_EM_RESOURCE T_EM_RESOURCE { get; set; }
        public virtual T_OE_USERS T_OE_USERS { get; set; }
    }
}
