//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_RESOURCE_DTL
    {
        public System.Guid RESOURCE_DTL_IDX { get; set; }
        public System.Guid RESOURCE_IDX { get; set; }
        public System.Guid RESOURCE_TYPE_DTL_IDX { get; set; }
        public string VALUE { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_EM_REF_RESOURCE_TYPE_DTL T_EM_REF_RESOURCE_TYPE_DTL { get; set; }
        public virtual T_EM_RESOURCE T_EM_RESOURCE { get; set; }
    }
}
