//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_USER_ORG
    {
        public System.Guid USER_ORG_IDX { get; set; }
        public int USER_IDX { get; set; }
        public System.Guid ORG_IDX { get; set; }
        public string ROLE_CD { get; set; }
        public string STATUS_CD { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_OE_ORGANIZATIONS T_OE_ORGANIZATIONS { get; set; }
        public virtual T_OE_USERS T_OE_USERS { get; set; }
    }
}
