//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_INCIDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EM_INCIDENT()
        {
            this.T_EM_INCIDENT_STATUS = new HashSet<T_EM_INCIDENT_STATUS>();
            this.T_EM_INCIDENT_LOC_AREA = new HashSet<T_EM_INCIDENT_LOC_AREA>();
            this.T_EM_INCIDENT_OP_PERIOD = new HashSet<T_EM_INCIDENT_OP_PERIOD>();
            this.T_EM_INCIDENT_TEAM_DTL = new HashSet<T_EM_INCIDENT_TEAM_DTL>();
            this.T_EM_INCIDENT_RESOURCES = new HashSet<T_EM_INCIDENT_RESOURCES>();
            this.T_EM_INCIDENT_ATTACH = new HashSet<T_EM_INCIDENT_ATTACH>();
        }
    
        public System.Guid INCIDENT_IDX { get; set; }
        public System.Guid ORG_IDX { get; set; }
        public string INCIDENT_ID { get; set; }
        public string INCIDENT_NAME { get; set; }
        public string INCIDENT_DESC { get; set; }
        public string INC_MANAGEMENT_ORG_CD { get; set; }
        public Nullable<System.DateTime> INCIDENT_START_DT { get; set; }
        public Nullable<System.DateTime> INCIDENT_END_DT { get; set; }
        public string INCIDENT_COMPLEX_LVL { get; set; }
        public string INCIDENT_LOC_DESC { get; set; }
        public Nullable<decimal> INCIDENT_LAT { get; set; }
        public Nullable<decimal> INCIDENT_LONG { get; set; }
        public string INCIDENT_STATE { get; set; }
        public Nullable<int> INCIDENT_CNTY { get; set; }
        public string INCIDENT_CITY { get; set; }
        public string INCIDENT_LAND_SURVEY { get; set; }
        public string INCIDENT_SIZE { get; set; }
        public string INCIDENT_SIZE_UNIT { get; set; }
        public Nullable<decimal> INCIDENT_PCT_CONTAINED { get; set; }
        public string INCIDENT_HAZ_MAT { get; set; }
        public string INCIDENT_WEATHER { get; set; }
        public Nullable<decimal> INCIDENT_COSTS { get; set; }
        public Nullable<decimal> INCIDENT_TOTAL_COSTS { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string SHARE_TYPE { get; set; }
        public string INCIDENT_PRIORITY { get; set; }
    
        public virtual T_EM_REF_MANAGEMENT_ORG T_EM_REF_MANAGEMENT_ORG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_STATUS> T_EM_INCIDENT_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_LOC_AREA> T_EM_INCIDENT_LOC_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_OP_PERIOD> T_EM_INCIDENT_OP_PERIOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_TEAM_DTL> T_EM_INCIDENT_TEAM_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_RESOURCES> T_EM_INCIDENT_RESOURCES { get; set; }
        public virtual T_EM_REF_COMPLEX_LVL T_EM_REF_COMPLEX_LVL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_ATTACH> T_EM_INCIDENT_ATTACH { get; set; }
        public virtual T_OE_ORGANIZATIONS T_OE_ORGANIZATIONS { get; set; }
        public virtual T_EM_REF_SHARE_TYPE T_EM_REF_SHARE_TYPE { get; set; }
        public virtual T_EM_REF_INCIDENT_PRIORITY T_EM_REF_INCIDENT_PRIORITY { get; set; }
    }
}
