//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_INCIDENT_TEAM_DTL
    {
        public System.Guid INCIDENT_TEAM_DTL_IDX { get; set; }
        public Nullable<System.Guid> INCIDENT_OP_PERIOD_IDX { get; set; }
        public Nullable<System.Guid> INCIDENT_IDX { get; set; }
        public Nullable<System.Guid> REPORTS_TO_TEAM_DTL_IDX { get; set; }
        public Nullable<System.Guid> INDIVIDUAL_IDX { get; set; }
        public Nullable<System.Guid> RESOURCE_IDX { get; set; }
        public string ROLE_NAME { get; set; }
        public string AGENCY { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public string TRAINEE_IND { get; set; }
        public string CONTACT_TYPE { get; set; }
        public string CONTACT_INFO { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_EM_INCIDENT T_EM_INCIDENT { get; set; }
        public virtual T_EM_INCIDENT_OP_PERIOD T_EM_INCIDENT_OP_PERIOD { get; set; }
        public virtual T_EM_INDIVIDUALS T_EM_INDIVIDUALS { get; set; }
        public virtual T_EM_RESOURCE T_EM_RESOURCE { get; set; }
    }
}
