//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_QUALIFICATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EM_QUALIFICATIONS()
        {
            this.T_EM_QUALIFICATION_ATTACH = new HashSet<T_EM_QUALIFICATION_ATTACH>();
        }
    
        public System.Guid QUALIFICATION_IDX { get; set; }
        public System.Guid ORG_IDX { get; set; }
        public System.Guid INDIVIDUAL_IDX { get; set; }
        public System.Guid QUAL_TYPE_IDX { get; set; }
        public Nullable<System.DateTime> EFF_DATE { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_EM_INDIVIDUALS T_EM_INDIVIDUALS { get; set; }
        public virtual T_OE_ORGANIZATIONS T_OE_ORGANIZATIONS { get; set; }
        public virtual T_EM_REF_QUAL_TYPE T_EM_REF_QUAL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_QUALIFICATION_ATTACH> T_EM_QUALIFICATION_ATTACH { get; set; }
    }
}
