//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_INDIVIDUALS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EM_INDIVIDUALS()
        {
            this.T_EM_INCIDENT_TEAM_DTL = new HashSet<T_EM_INCIDENT_TEAM_DTL>();
            this.T_EM_QUALIFICATIONS = new HashSet<T_EM_QUALIFICATIONS>();
        }
    
        public System.Guid INDIVIDUAL_IDX { get; set; }
        public System.Guid ORG_IDX { get; set; }
        public string INDV_FIRST_NAME { get; set; }
        public string INDV_MID_NAME { get; set; }
        public string INDV_LAST_NAME { get; set; }
        public Nullable<System.DateTime> INDV_DOB { get; set; }
        public string INDV_PHONE { get; set; }
        public string INDV_EMAIL { get; set; }
        public string ADD_LINE_ADR { get; set; }
        public string ADD_CITY { get; set; }
        public string ADD_STATE { get; set; }
        public string ADD_ZIP { get; set; }
        public Nullable<int> LINKED_USERIDX { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string INDV_AFFILIATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT_TEAM_DTL> T_EM_INCIDENT_TEAM_DTL { get; set; }
        public virtual T_OE_USERS T_OE_USERS { get; set; }
        public virtual T_OE_ORGANIZATIONS T_OE_ORGANIZATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_QUALIFICATIONS> T_EM_QUALIFICATIONS { get; set; }
    }
}
