//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EM_REF_SHARE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_EM_REF_SHARE_TYPE()
        {
            this.T_EM_DOCUMENTS = new HashSet<T_EM_DOCUMENTS>();
            this.T_EM_RESOURCE = new HashSet<T_EM_RESOURCE>();
            this.T_EM_INCIDENT = new HashSet<T_EM_INCIDENT>();
        }
    
        public string SHARE_TYPE { get; set; }
        public string SHARE_DESC { get; set; }
        public bool ACT_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_DOCUMENTS> T_EM_DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_RESOURCE> T_EM_RESOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT> T_EM_INCIDENT { get; set; }
    }
}
