//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OE_USER_TOKENS
    {
        public int USER_IDX { get; set; }
        public System.Guid USER_TOKEN_IDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
    
        public virtual T_OE_USERS T_OE_USERS { get; set; }
    }
}
