//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OE_APP_SETTINGS
    {
        public int SETTING_IDX { get; set; }
        public string SETTING_NAME { get; set; }
        public string SETTING_VALUE { get; set; }
        public Nullable<bool> ENCRYPT_IND { get; set; }
        public string SETTING_VALUE_SALT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    }
}
