//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OE_ORGANIZATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_OE_ORGANIZATIONS()
        {
            this.T_EM_DOCUMENTS = new HashSet<T_EM_DOCUMENTS>();
            this.T_EM_INCIDENT = new HashSet<T_EM_INCIDENT>();
            this.T_EM_INDIVIDUALS = new HashSet<T_EM_INDIVIDUALS>();
            this.T_EM_QUALIFICATIONS = new HashSet<T_EM_QUALIFICATIONS>();
            this.T_EM_REF_QUAL_TYPE = new HashSet<T_EM_REF_QUAL_TYPE>();
            this.T_EM_REF_RESOURCE_TYPE = new HashSet<T_EM_REF_RESOURCE_TYPE>();
            this.T_EM_RESOURCE = new HashSet<T_EM_RESOURCE>();
            this.T_EM_USER_ORG = new HashSet<T_EM_USER_ORG>();
        }
    
        public System.Guid ORG_IDX { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_DESC { get; set; }
        public Nullable<bool> ALLOW_JOIN_IND { get; set; }
        public bool ACT_IND { get; set; }
        public Nullable<int> CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public Nullable<int> MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_DOCUMENTS> T_EM_DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INCIDENT> T_EM_INCIDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_INDIVIDUALS> T_EM_INDIVIDUALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_QUALIFICATIONS> T_EM_QUALIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_REF_QUAL_TYPE> T_EM_REF_QUAL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_REF_RESOURCE_TYPE> T_EM_REF_RESOURCE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_RESOURCE> T_EM_RESOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EM_USER_ORG> T_EM_USER_ORG { get; set; }
    }
}
