//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergencyHoundModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EM_TIMELINE
    {
        public Nullable<long> TIMELINE_IDX { get; set; }
        public System.Guid INCIDENT_IDX { get; set; }
        public Nullable<System.DateTime> TIMELINE_DT { get; set; }
        public string UPDATE_TYPE { get; set; }
        public string NME { get; set; }
        public System.Guid KEY_IDX { get; set; }
    }
}
