//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EmergencyHoundWeb.org.preptoolkit.rtlt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_WebService", Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Definition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PagedResult))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMissionAreasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCoreCapabilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceKindsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceHeadersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPositionHeadersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPositionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPositionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::EmergencyHoundWeb.Properties.Settings.Default.EmergencyHoundWeb_org_preptoolkit_rtlt_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCategoriesCompletedEventHandler GetCategoriesCompleted;
        
        /// <remarks/>
        public event GetMissionAreasCompletedEventHandler GetMissionAreasCompleted;
        
        /// <remarks/>
        public event GetCoreCapabilitiesCompletedEventHandler GetCoreCapabilitiesCompleted;
        
        /// <remarks/>
        public event GetResourceKindsCompletedEventHandler GetResourceKindsCompleted;
        
        /// <remarks/>
        public event GetResourceHeadersCompletedEventHandler GetResourceHeadersCompleted;
        
        /// <remarks/>
        public event GetResourcesCompletedEventHandler GetResourcesCompleted;
        
        /// <remarks/>
        public event GetResourceCompletedEventHandler GetResourceCompleted;
        
        /// <remarks/>
        public event GetPositionHeadersCompletedEventHandler GetPositionHeadersCompleted;
        
        /// <remarks/>
        public event GetPositionsCompletedEventHandler GetPositionsCompleted;
        
        /// <remarks/>
        public event GetPositionCompletedEventHandler GetPositionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetCategories", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Category[] GetCategories() {
            object[] results = this.Invoke("GetCategories", new object[0]);
            return ((Category[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(object userState) {
            if ((this.GetCategoriesOperationCompleted == null)) {
                this.GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCategories", new object[0], this.GetCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCategoriesOperationCompleted(object arg) {
            if ((this.GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetMissionAreas", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MissionArea[] GetMissionAreas() {
            object[] results = this.Invoke("GetMissionAreas", new object[0]);
            return ((MissionArea[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMissionAreasAsync() {
            this.GetMissionAreasAsync(null);
        }
        
        /// <remarks/>
        public void GetMissionAreasAsync(object userState) {
            if ((this.GetMissionAreasOperationCompleted == null)) {
                this.GetMissionAreasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMissionAreasOperationCompleted);
            }
            this.InvokeAsync("GetMissionAreas", new object[0], this.GetMissionAreasOperationCompleted, userState);
        }
        
        private void OnGetMissionAreasOperationCompleted(object arg) {
            if ((this.GetMissionAreasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMissionAreasCompleted(this, new GetMissionAreasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetCoreCapabilities", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CoreCapability[] GetCoreCapabilities() {
            object[] results = this.Invoke("GetCoreCapabilities", new object[0]);
            return ((CoreCapability[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCoreCapabilitiesAsync() {
            this.GetCoreCapabilitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetCoreCapabilitiesAsync(object userState) {
            if ((this.GetCoreCapabilitiesOperationCompleted == null)) {
                this.GetCoreCapabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCoreCapabilitiesOperationCompleted);
            }
            this.InvokeAsync("GetCoreCapabilities", new object[0], this.GetCoreCapabilitiesOperationCompleted, userState);
        }
        
        private void OnGetCoreCapabilitiesOperationCompleted(object arg) {
            if ((this.GetCoreCapabilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCoreCapabilitiesCompleted(this, new GetCoreCapabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetResourceKinds", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Kind[] GetResourceKinds() {
            object[] results = this.Invoke("GetResourceKinds", new object[0]);
            return ((Kind[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceKindsAsync() {
            this.GetResourceKindsAsync(null);
        }
        
        /// <remarks/>
        public void GetResourceKindsAsync(object userState) {
            if ((this.GetResourceKindsOperationCompleted == null)) {
                this.GetResourceKindsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceKindsOperationCompleted);
            }
            this.InvokeAsync("GetResourceKinds", new object[0], this.GetResourceKindsOperationCompleted, userState);
        }
        
        private void OnGetResourceKindsOperationCompleted(object arg) {
            if ((this.GetResourceKindsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceKindsCompleted(this, new GetResourceKindsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetResourceHeaders", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DefinitionHeaderSet GetResourceHeaders([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedFrom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedTo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string category, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string missionArea, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string coreCapability, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kind, int page, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified) {
            object[] results = this.Invoke("GetResourceHeaders", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        kind,
                        page,
                        pageSpecified});
            return ((DefinitionHeaderSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceHeadersAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, string kind, int page, bool pageSpecified) {
            this.GetResourceHeadersAsync(name, status, updatedFrom, updatedTo, category, missionArea, coreCapability, kind, page, pageSpecified, null);
        }
        
        /// <remarks/>
        public void GetResourceHeadersAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, string kind, int page, bool pageSpecified, object userState) {
            if ((this.GetResourceHeadersOperationCompleted == null)) {
                this.GetResourceHeadersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceHeadersOperationCompleted);
            }
            this.InvokeAsync("GetResourceHeaders", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        kind,
                        page,
                        pageSpecified}, this.GetResourceHeadersOperationCompleted, userState);
        }
        
        private void OnGetResourceHeadersOperationCompleted(object arg) {
            if ((this.GetResourceHeadersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceHeadersCompleted(this, new GetResourceHeadersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetResources", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResourceDefinitionSet GetResources([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedFrom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedTo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string category, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string missionArea, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string coreCapability, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kind, int page, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified) {
            object[] results = this.Invoke("GetResources", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        kind,
                        page,
                        pageSpecified});
            return ((ResourceDefinitionSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourcesAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, string kind, int page, bool pageSpecified) {
            this.GetResourcesAsync(name, status, updatedFrom, updatedTo, category, missionArea, coreCapability, kind, page, pageSpecified, null);
        }
        
        /// <remarks/>
        public void GetResourcesAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, string kind, int page, bool pageSpecified, object userState) {
            if ((this.GetResourcesOperationCompleted == null)) {
                this.GetResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourcesOperationCompleted);
            }
            this.InvokeAsync("GetResources", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        kind,
                        page,
                        pageSpecified}, this.GetResourcesOperationCompleted, userState);
        }
        
        private void OnGetResourcesOperationCompleted(object arg) {
            if ((this.GetResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourcesCompleted(this, new GetResourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetResource", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResourceDefinition GetResource([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("GetResource", new object[] {
                        id});
            return ((ResourceDefinition)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceAsync(string id) {
            this.GetResourceAsync(id, null);
        }
        
        /// <remarks/>
        public void GetResourceAsync(string id, object userState) {
            if ((this.GetResourceOperationCompleted == null)) {
                this.GetResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceOperationCompleted);
            }
            this.InvokeAsync("GetResource", new object[] {
                        id}, this.GetResourceOperationCompleted, userState);
        }
        
        private void OnGetResourceOperationCompleted(object arg) {
            if ((this.GetResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceCompleted(this, new GetResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetPositionHeaders", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DefinitionHeaderSet GetPositionHeaders([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedFrom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedTo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string category, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string missionArea, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string coreCapability, int page, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified) {
            object[] results = this.Invoke("GetPositionHeaders", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        page,
                        pageSpecified});
            return ((DefinitionHeaderSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPositionHeadersAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, int page, bool pageSpecified) {
            this.GetPositionHeadersAsync(name, status, updatedFrom, updatedTo, category, missionArea, coreCapability, page, pageSpecified, null);
        }
        
        /// <remarks/>
        public void GetPositionHeadersAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, int page, bool pageSpecified, object userState) {
            if ((this.GetPositionHeadersOperationCompleted == null)) {
                this.GetPositionHeadersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionHeadersOperationCompleted);
            }
            this.InvokeAsync("GetPositionHeaders", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        page,
                        pageSpecified}, this.GetPositionHeadersOperationCompleted, userState);
        }
        
        private void OnGetPositionHeadersOperationCompleted(object arg) {
            if ((this.GetPositionHeadersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionHeadersCompleted(this, new GetPositionHeadersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetPositions", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PositionDefinitionSet GetPositions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedFrom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string updatedTo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string category, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string missionArea, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string coreCapability, int page, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSpecified) {
            object[] results = this.Invoke("GetPositions", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        page,
                        pageSpecified});
            return ((PositionDefinitionSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPositionsAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, int page, bool pageSpecified) {
            this.GetPositionsAsync(name, status, updatedFrom, updatedTo, category, missionArea, coreCapability, page, pageSpecified, null);
        }
        
        /// <remarks/>
        public void GetPositionsAsync(string name, string status, string updatedFrom, string updatedTo, string category, string missionArea, string coreCapability, int page, bool pageSpecified, object userState) {
            if ((this.GetPositionsOperationCompleted == null)) {
                this.GetPositionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionsOperationCompleted);
            }
            this.InvokeAsync("GetPositions", new object[] {
                        name,
                        status,
                        updatedFrom,
                        updatedTo,
                        category,
                        missionArea,
                        coreCapability,
                        page,
                        pageSpecified}, this.GetPositionsOperationCompleted, userState);
        }
        
        private void OnGetPositionsOperationCompleted(object arg) {
            if ((this.GetPositionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionsCompleted(this, new GetPositionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ptaccenter.org/Rtlt.Core.Api.V2/WebService/GetPosition", RequestNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", ResponseNamespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PositionDefinition GetPosition([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("GetPosition", new object[] {
                        id});
            return ((PositionDefinition)(results[0]));
        }
        
        /// <remarks/>
        public void GetPositionAsync(string id) {
            this.GetPositionAsync(id, null);
        }
        
        /// <remarks/>
        public void GetPositionAsync(string id, object userState) {
            if ((this.GetPositionOperationCompleted == null)) {
                this.GetPositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPositionOperationCompleted);
            }
            this.InvokeAsync("GetPosition", new object[] {
                        id}, this.GetPositionOperationCompleted, userState);
        }
        
        private void OnGetPositionOperationCompleted(object arg) {
            if ((this.GetPositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPositionCompleted(this, new GetPositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class Category {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionNote {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string noteField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionReference {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string referenceField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionOrdering {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string specificationField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Specification {
            get {
                return this.specificationField;
            }
            set {
                this.specificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionCategoryType {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string typeField;
        
        private string criteriaField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionCategory {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string categoryField;
        
        private string notesField;
        
        private PositionCategoryType[] typesField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionCategoryType[] Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionType {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string typeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionSupportingCoreCapability {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceNote {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string noteField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceReference {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string referenceField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceComment {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string commentField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceCapabilityType {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string typeField;
        
        private string attributeField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceCapability {
        
        private int orderField;
        
        private bool orderFieldSpecified;
        
        private string componentField;
        
        private string metricField;
        
        private string abilityField;
        
        private string notesField;
        
        private ResourceCapabilityType[] typesField;
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Component {
            get {
                return this.componentField;
            }
            set {
                this.componentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Metric {
            get {
                return this.metricField;
            }
            set {
                this.metricField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ability {
            get {
                return this.abilityField;
            }
            set {
                this.abilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceCapabilityType[] Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceSupportingCoreCapability {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class Definition {
        
        private string idField;
        
        private int tierField;
        
        private bool tierFieldSpecified;
        
        private string nameField;
        
        private string statusField;
        
        private string statusDescriptionField;
        
        private System.DateTime updatedField;
        
        private bool updatedFieldSpecified;
        
        private System.Nullable<System.DateTime> releasedField;
        
        private bool releasedFieldSpecified;
        
        private string categoryField;
        
        private int categoryNumberField;
        
        private bool categoryNumberFieldSpecified;
        
        private string primaryCoreCapabilityField;
        
        private string secondaryCoreCapabilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Tier {
            get {
                return this.tierField;
            }
            set {
                this.tierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TierSpecified {
            get {
                return this.tierFieldSpecified;
            }
            set {
                this.tierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Released {
            get {
                return this.releasedField;
            }
            set {
                this.releasedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleasedSpecified {
            get {
                return this.releasedFieldSpecified;
            }
            set {
                this.releasedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryNumber {
            get {
                return this.categoryNumberField;
            }
            set {
                this.categoryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryNumberSpecified {
            get {
                return this.categoryNumberFieldSpecified;
            }
            set {
                this.categoryNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PrimaryCoreCapability {
            get {
                return this.primaryCoreCapabilityField;
            }
            set {
                this.primaryCoreCapabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondaryCoreCapability {
            get {
                return this.secondaryCoreCapabilityField;
            }
            set {
                this.secondaryCoreCapabilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionDefinition : Definition {
        
        private PositionSupportingCoreCapability[] supportingCoreCapabilitiesField;
        
        private PositionType[] typesField;
        
        private PositionCategory[] categoriesField;
        
        private bool isIndividualField;
        
        private bool isIndividualFieldSpecified;
        
        private bool isWithTeamField;
        
        private bool isWithTeamFieldSpecified;
        
        private string teamField;
        
        private bool isWithUnitField;
        
        private bool isWithUnitFieldSpecified;
        
        private string unitField;
        
        private PositionOrdering[] orderingSpecificationsField;
        
        private PositionReference[] referencesField;
        
        private PositionNote[] notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionSupportingCoreCapability[] SupportingCoreCapabilities {
            get {
                return this.supportingCoreCapabilitiesField;
            }
            set {
                this.supportingCoreCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionType[] Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionCategory[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        public bool IsIndividual {
            get {
                return this.isIndividualField;
            }
            set {
                this.isIndividualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsIndividualSpecified {
            get {
                return this.isIndividualFieldSpecified;
            }
            set {
                this.isIndividualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsWithTeam {
            get {
                return this.isWithTeamField;
            }
            set {
                this.isWithTeamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsWithTeamSpecified {
            get {
                return this.isWithTeamFieldSpecified;
            }
            set {
                this.isWithTeamFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWithUnit {
            get {
                return this.isWithUnitField;
            }
            set {
                this.isWithUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsWithUnitSpecified {
            get {
                return this.isWithUnitFieldSpecified;
            }
            set {
                this.isWithUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionOrdering[] OrderingSpecifications {
            get {
                return this.orderingSpecificationsField;
            }
            set {
                this.orderingSpecificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionReference[] References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionNote[] Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceDefinition : Definition {
        
        private ResourceSupportingCoreCapability[] supportingCoreCapabilitiesField;
        
        private string descriptionField;
        
        private string kindField;
        
        private string overallFunctionField;
        
        private string compositionOrderingField;
        
        private ResourceCapability[] capabilitiesField;
        
        private ResourceComment[] commentsField;
        
        private ResourceReference[] referencesField;
        
        private ResourceNote[] notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceSupportingCoreCapability[] SupportingCoreCapabilities {
            get {
                return this.supportingCoreCapabilitiesField;
            }
            set {
                this.supportingCoreCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OverallFunction {
            get {
                return this.overallFunctionField;
            }
            set {
                this.overallFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompositionOrdering {
            get {
                return this.compositionOrderingField;
            }
            set {
                this.compositionOrderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceCapability[] Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceComment[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceReference[] References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceNote[] Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class DefinitionHeader {
        
        private string idField;
        
        private string nameField;
        
        private string statusField;
        
        private System.DateTime updatedField;
        
        private bool updatedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionDefinitionSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceDefinitionSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefinitionHeaderSet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PagedResult {
        
        private int itemCountField;
        
        private bool itemCountFieldSpecified;
        
        private int pageCountField;
        
        private bool pageCountFieldSpecified;
        
        private int pageField;
        
        private bool pageFieldSpecified;
        
        private int pageItemCountField;
        
        private bool pageItemCountFieldSpecified;
        
        /// <remarks/>
        public int ItemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemCountSpecified {
            get {
                return this.itemCountFieldSpecified;
            }
            set {
                this.itemCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageCountSpecified {
            get {
                return this.pageCountFieldSpecified;
            }
            set {
                this.pageCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageSpecified {
            get {
                return this.pageFieldSpecified;
            }
            set {
                this.pageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PageItemCount {
            get {
                return this.pageItemCountField;
            }
            set {
                this.pageItemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageItemCountSpecified {
            get {
                return this.pageItemCountFieldSpecified;
            }
            set {
                this.pageItemCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class PositionDefinitionSet : PagedResult {
        
        private PositionDefinition[] definitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PositionDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class ResourceDefinitionSet : PagedResult {
        
        private ResourceDefinition[] definitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResourceDefinition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class DefinitionHeaderSet : PagedResult {
        
        private DefinitionHeader[] headersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DefinitionHeader[] Headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class Kind {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class CoreCapability {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class MissionAreaCoreCapability {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ptaccenter.org/Rtlt.Core.Api.V2")]
    public partial class MissionArea {
        
        private string nameField;
        
        private MissionAreaCoreCapability[] coreCapabilitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MissionAreaCoreCapability[] CoreCapabilities {
            get {
                return this.coreCapabilitiesField;
            }
            set {
                this.coreCapabilitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetCategoriesCompletedEventHandler(object sender, GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Category[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Category[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetMissionAreasCompletedEventHandler(object sender, GetMissionAreasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMissionAreasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMissionAreasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MissionArea[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MissionArea[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetCoreCapabilitiesCompletedEventHandler(object sender, GetCoreCapabilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCoreCapabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCoreCapabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CoreCapability[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CoreCapability[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetResourceKindsCompletedEventHandler(object sender, GetResourceKindsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceKindsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceKindsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Kind[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Kind[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetResourceHeadersCompletedEventHandler(object sender, GetResourceHeadersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceHeadersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceHeadersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DefinitionHeaderSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DefinitionHeaderSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetResourcesCompletedEventHandler(object sender, GetResourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceDefinitionSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceDefinitionSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetResourceCompletedEventHandler(object sender, GetResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceDefinition Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceDefinition)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetPositionHeadersCompletedEventHandler(object sender, GetPositionHeadersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionHeadersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPositionHeadersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DefinitionHeaderSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DefinitionHeaderSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetPositionsCompletedEventHandler(object sender, GetPositionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPositionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PositionDefinitionSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PositionDefinitionSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetPositionCompletedEventHandler(object sender, GetPositionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PositionDefinition Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PositionDefinition)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591